export const USER_QUESTIONNAIRE_CHANGING_SCENE = 'USER_QUESTIONNAIRE_CHANGING_SCENE'
export const USER_QUESTIONNAIRE_SETTINGS_SCENE = 'USER_QUESTIONNAIRE_SETTINGS_SCENE'
export const USER_WAIT_LIKE_SCENE = 'USER_WAIT_LIKE_SCENE'
